mode: "denovo" # "denovo" or "refmap"

raw_fastq: # single-end currently not supported
  forward: "example_data/test_R1_001.fastq.gz" 
  reverse: "example_data/test_R2_001.fastq.gz"

cutadapt:
  adapter: "AGATCGGAAGAGC" # Sequence of the adapter
  length: "50" # Mininimum length for refmap, common length for denovo
  minimum_phred: "25"  # Changed '=' to ':'

genome: # only needed for refmap mode
  ref: "genome/stoneflygenomeassemblyv1.fasta"

vcf_filtering:
  parameters: "--max-missing 0.8 --maf 0.0001" # vcftools arguments, passed at once
